# Custom nav
nav:
  title: "Jerry"
  subTitle: "Focus on Frontend"

favicon: ""

# Custom background
background:
  color: "#eff0f6"
  image: ""

# Social media
social:
  # Dribbble: https://dribbble.com/
  # Behance: https://www.behance.net/
  # Lofter: http://lofter.com/
  # Instagram: https://www.instagram.com/
  GitHub: https://github.com/xuxji
  Yuque: https://www.yuque.com/xiaoji
  Guitar: Guitar
  Basketball: Basketball
  # Weibo: https://weibo.com/xuxji

# Custom footer
mail: xuxji.123@163.com
copyright: Theme based on @Clover Tuan

# Custom menu. You can specific the path or the card style (only useful for category page).
# Two kinds of card style: 'project-card', 'article-card',
# Never mind the name.
menu:
  # Project:
  #   path: /categories/Projects
  #   card: project-card
  # Stuffs:
  #   path: /tags/Stuffs
  #   card: article-card
  Home: /
  Archive: /archives
  About: /about

# Specific default categories or tags of home page.
# Post which belongs to `category` or `tag` and don't belongs to `except_category` or `except_tag` will be filtered.
home:
  # set card style of home page
  # category: Projects
  # tag: react
  # except_category: 树
  # except_tag:
  #   - 总结
  #   - css

card_style:
  home: project-card
  archive: article-card
  tag: article-card
  category: article-card

# category page
category_generator:
  category_per_page: 5
  post_per_category: 5

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false